#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 10, 2019 07:28:35 PM CEST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import elDestripador_support
#from Tkinter import *
#from HoverInfo import HoverInfo

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    elDestripador_support.set_Tk_var()
    top = Toplevel1 (root)
    elDestripador_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    elDestripador_support.set_Tk_var()
    top = Toplevel1 (w)
    elDestripador_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("853x581+512+208")
        top.title("John The Ripper")
        top.configure(highlightcolor="black")

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.059, rely=0.069, relwidth=0.879)

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.234, rely=0.086, height=31, width=96)
        self.Button1.configure(activebackground="#f9f9f9")
        self.Button1.configure(command=elDestripador_support.unshadow)
        self.Button1.configure(text='''Unshadow''')

        self.Checkbutton = tk.Checkbutton(top)
        self.Checkbutton.place(relx=0.117, rely=0.172, relheight=0.04
                , relwidth=0.079)
        self.Checkbutton.configure(activebackground="#f9f9f9")
        self.Checkbutton.configure(command=elDestripador_support.singleCeck)
        self.Checkbutton.configure(justify='left')
        self.Checkbutton.configure(text='''Single''')
        self.Checkbutton.configure(variable=elDestripador_support.che44)

        self.Checkbutton2 = tk.Checkbutton(top)
        self.Checkbutton2.place(relx=0.117, rely=0.241, relheight=0.04
                , relwidth=0.095)
        self.Checkbutton2.configure(activebackground="#f9f9f9")
        self.Checkbutton2.configure(command=elDestripador_support.wordlistCheck)
        self.Checkbutton2.configure(justify='left')
        self.Checkbutton2.configure(text='''Wordlist''')
        self.Checkbutton2.configure(variable=elDestripador_support.che45)

        self.Checkbutton3 = tk.Checkbutton(top)
        self.Checkbutton3.place(relx=0.117, rely=0.31, relheight=0.04
                , relwidth=0.123)
        self.Checkbutton3.configure(activebackground="#f9f9f9")
        self.Checkbutton3.configure(command=elDestripador_support.incrementalCheck)
        self.Checkbutton3.configure(justify='left')
        self.Checkbutton3.configure(text='''Incremental''')
        self.Checkbutton3.configure(variable=elDestripador_support.che46)

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.281, rely=0.241,height=23, relwidth=0.195)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(selectbackground="#c4c4c4")

        self.Checkbutton4 = tk.Checkbutton(top)
        self.Checkbutton4.place(relx=0.539, rely=0.095, relheight=0.04
                , relwidth=0.12)
        self.Checkbutton4.configure(activebackground="#f9f9f9")
        self.Checkbutton4.configure(command=elDestripador_support.customFileCheck)
        self.Checkbutton4.configure(justify='left')
        self.Checkbutton4.configure(text='''Custom file''')
        self.Checkbutton4.configure(variable=elDestripador_support.che50)

        self.TCombobox1 = ttk.Combobox(top)
        self.TCombobox1.place(relx=0.281, rely=0.31, relheight=0.036
                , relwidth=0.254)
        self.value_list = ['ASCII','Alnum','Alpha','LowerNum','UpperNum','LowerSpace','Lower','Upper','Digits',]
        self.TCombobox1.configure(values=self.value_list)
        self.TCombobox1.configure(textvariable=elDestripador_support.combobox)
        self.TCombobox1.configure(foreground="#000000")
        self.TCombobox1.configure(takefocus="")

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.692, rely=0.095,height=23, relwidth=0.183)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(state='disabled')

        self.Button5 = tk.Button(top)
        self.Button5.place(relx=0.469, rely=0.241, height=23, width=58)
        self.Button5.configure(activebackground="#f9f9f9")
        self.Button5.configure(command=elDestripador_support.selectWordlist)
        self.Button5.configure(text='''Select''')

        self.Button6 = tk.Button(top)
        self.Button6.place(relx=0.868, rely=0.095, height=23, width=58)
        self.Button6.configure(activebackground="#f9f9f9")
        self.Button6.configure(command=elDestripador_support.selectCustomFile)
        self.Button6.configure(state='disabled')
        self.Button6.configure(text='''Select''')

        self.Scrolledtext1 = ScrolledText(top)
        self.Scrolledtext1.place(relx=0.059, rely=0.482, relheight=0.391
                , relwidth=0.877)
        self.Scrolledtext1.configure(background="white")
        self.Scrolledtext1.configure(font="TkTextFont")
        self.Scrolledtext1.configure(insertborderwidth="3")
        self.Scrolledtext1.configure(selectbackground="#c4c4c4")
        self.Scrolledtext1.configure(width=10)
        self.Scrolledtext1.configure(wrap="none")

        self.Button7 = tk.Button(top)
        self.Button7.place(relx=0.387, rely=0.413, height=31, width=191)
        self.Button7.configure(activebackground="#f9f9f9")
        self.Button7.configure(command=elDestripador_support.crackedPasswd)
        self.Button7.configure(text='''Show cracked passwords''')

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.469, rely=0.017, height=21, width=46)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(text='''Config''')

        self.TSeparator2 = ttk.Separator(top)
        self.TSeparator2.place(relx=0.059, rely=0.155, relwidth=0.879)

        self.TSeparator3 = ttk.Separator(top)
        self.TSeparator3.place(relx=0.492, rely=0.069, relheight=0.086)
        self.TSeparator3.configure(orient="vertical")

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.774, rely=0.224, height=61, width=109)
        self.Button2.configure(activebackground="#f9f9f9")
        self.Button2.configure(command=elDestripador_support.startBut)
        self.Button2.configure(font="-family {DejaVu Sans} -size 20")
        self.Button2.configure(state='disabled')
        self.Button2.configure(text='''Start''')

        self.TSeparator4 = ttk.Separator(top)
        self.TSeparator4.place(relx=0.059, rely=0.379, relwidth=0.879)

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.574, rely=0.241, height=21, width=131)
        self.Button3.configure(activebackground="#f9f9f9")
        self.Button3.configure(command=elDestripador_support.openCrunch)
        self.Button3.configure(state='disabled')
        self.Button3.configure(text='''Generate Wordlist''')

        self.Button4 = tk.Button(top)
        self.Button4.place(relx=0.574, rely=0.31, height=21, width=82)
        self.Button4.configure(activebackground="#f9f9f9")
        self.Button4.configure(command=elDestripador_support.openAdvancedIncremental)
        self.Button4.configure(state='disabled')
        self.Button4.configure(text='''Advanced''')

        self.Button8 = tk.Button(top)
        self.Button8.place(relx=0.059, rely=0.912, height=31, width=62)
        self.Button8.configure(activebackground="#f9f9f9")
        self.Button8.configure(command=elDestripador_support.clearText)
        self.Button8.configure(text='''Clear''')

        self.Button9 = tk.Button(top)
        self.Button9.place(relx=0.879, rely=0.912, height=31, width=55)
        self.Button9.configure(activebackground="#f9f9f9")
        self.Button9.configure(command=elDestripador_support.quit)
        self.Button9.configure(text='''Quit''')

        self.Button10 = tk.Button(top)
        self.Button10.place(relx=0.961, rely=0.017, height=21, width=21)
        self.Button10.configure(command=elDestripador_support.help)
        self.Button10.configure(text='''?''')
        self.Button10.configure(width=21)
        #self.Button10 = HoverInfo(self.Button10, 'while hovering press return \n for an exciting msg')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.41, rely=0.964, height=17, width=137)
        self.Label2.configure(font="-family {DejaVu Sans} -size 8")
        self.Label2.configure(text='''Created by: Ivan & Kevin''')

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.post(event.x_root, event.y_root)

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, tk.Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





