#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 13, 2019 08:22:24 PM CEST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import menu_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    menu_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    menu_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font13 = "-family {DejaVu Sans} -size 10"

        top.geometry("336x474+766+288")
        top.title("NCJM Interface")
        top.configure(highlightcolor="black")

        self.Butcamp = tk.Button(top)
        self.Butcamp.place(relx=0.298, rely=0.274, height=31, width=140)
        self.Butcamp.configure(activebackground="#f9f9f9")
        self.Butcamp.configure(command=menu_support.install)
        self.Butcamp.configure(state='disabled')
        self.Butcamp.configure(text='''Install Requisites''')

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.298, rely=0.38, height=31, width=140)
        self.Button2.configure(activebackground="#f9f9f9")
        self.Button2.configure(command=menu_support.callnmap)
        self.Button2.configure(text='''Nmap''')
        self.Button2.configure(width=140)

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.298, rely=0.485, height=31, width=140)
        self.Button3.configure(activebackground="#f9f9f9")
        self.Button3.configure(command=menu_support.crunch)
        self.Button3.configure(text='''Crunch''')
        self.Button3.configure(width=140)

        self.Button4 = tk.Button(top)
        self.Button4.place(relx=0.417, rely=0.865, height=31, width=53)
        self.Button4.configure(activebackground="#f9f9f9")
        self.Button4.configure(command=menu_support.quit)
        self.Button4.configure(text='''Exit''')

        self.lab48 = tk.Label(top)
        self.lab48.place(relx=0.149, rely=0.063, height=81, width=247)
        self.lab48.configure(activebackground="#000000")
        self.lab48.configure(activeforeground="white")
        self.lab48.configure(activeforeground="#1aef28")
        self.lab48.configure(background="#262626")
        self.lab48.configure(font="-family {DejaVu Sans} -size 24")
        self.lab48.configure(state='active')
        self.lab48.configure(text='''NCJM''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.298, rely=0.591, height=31, width=140)
        self.Button1.configure(activebackground="#f9f9f9")
        self.Button1.configure(command=menu_support.john)
        self.Button1.configure(takefocus="0")
        self.Button1.configure(text='''John De Ripper''')

        self.Button6 = tk.Button(top)
        self.Button6.place(relx=0.298, rely=0.696, height=31, width=140)
        self.Button6.configure(activebackground="#f9f9f9")
        self.Button6.configure(command=menu_support.medusa)
        self.Button6.configure(takefocus="0")
        self.Button6.configure(text='''Medusa''')

        self.menubar = tk.Menu(top, font=('DejaVu Sans', 10, ), bg=_bgcolor
                ,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Button7 = tk.Button(top)
        self.Button7.place(relx=0.923, rely=0.0, height=20, width=20)
        self.Button7.configure(activebackground="#f9f9f9")
        self.Button7.configure(command=menu_support.help)
        self.Button7.configure(takefocus="0")
        self.Button7.configure(text='''?''')

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.298, rely=0.949, height=17, width=137)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(font="-family {DejaVu Sans} -size 8")
        self.Label1.configure(text='''Created by: Ivan & Keivn''')

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()
