#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  May 10, 2019 07:23:47 PM CEST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set desc "-family {DejaVu Sans Mono} -size 10"
set vTcl(actual_gui_font_fixed_desc) $desc
set vTcl(actual_gui_font_fixed_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_tooltip_desc) $desc
set vTcl(actual_gui_font_tooltip_name) [font create {*}$desc]
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {DejaVu Sans} -size 8 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font19
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#
    menu .pop43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop43" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x697+651+165
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Crunch"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    button $top.but43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command generate -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text Generate 
    vTcl:DefineAlias "$top.but43" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Make Wordlist with Crunch} 
    vTcl:DefineAlias "$top.lab44" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Min 
    vTcl:DefineAlias "$top.lab45" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Max 
    vTcl:DefineAlias "$top.lab48" "Label5" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent52 \
        -background white -font {-family {DejaVu Sans Mono} -size 10} \
        -foreground {#000000} -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent52" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent53 \
        -background white -font {-family {DejaVu Sans Mono} -size 10} \
        -foreground {#000000} -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent53" "Entry1_2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent54 \
        -background white -font {-family {DejaVu Sans Mono} -size 10} \
        -foreground {#000000} -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -state disabled 
    vTcl:DefineAlias "$top.ent54" "Entry1_3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent55 \
        -background white -font {-family {DejaVu Sans Mono} -size 10} \
        -foreground {#000000} -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -state disabled 
    vTcl:DefineAlias "$top.ent55" "Entry1_4" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent57 \
        -background white -font {-family {DejaVu Sans Mono} -size 10} \
        -foreground {#000000} -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -state disabled 
    vTcl:DefineAlias "$top.ent57" "Entry1_6" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent59 \
        -background white -font {-family {DejaVu Sans Mono} -size 10} \
        -foreground {#000000} -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -state disabled 
    vTcl:DefineAlias "$top.ent59" "Entry1_8" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe60
    vTcl:DefineAlias "$top.tSe60" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che64 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command destinFile -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -justify left \
        -text {Destination File} -variable che64 
    vTcl:DefineAlias "$top.che64" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che65 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command restricChar -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -justify left \
        -text {Restricted Characters} -variable che64 
    vTcl:DefineAlias "$top.che65" "Checkbutton1_10" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command mixedChar -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -justify left \
        -text {Mixed Characters} -variable che64 
    vTcl:DefineAlias "$top.che67" "Checkbutton1_12" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che69 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command mixedWord -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -justify left \
        -text {Mixed Words} -variable che64 
    vTcl:DefineAlias "$top.che69" "Checkbutton1_14" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Custom Crunch} 
    vTcl:DefineAlias "$top.lab43" "Label3" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe44
    vTcl:DefineAlias "$top.tSe44" "TSeparator2" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe45
    vTcl:DefineAlias "$top.tSe45" "TSeparator3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent47 \
        -background white -font {-family {DejaVu Sans Mono} -size 10} \
        -foreground {#000000} -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent47" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command buttonperson -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text ¡GO! 
    vTcl:DefineAlias "$top.but48" "Button2" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe49
    vTcl:DefineAlias "$top.tSe49" "TSeparator4" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr50 \
        -background {#d9d9d9} -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr50" "Scrolledtext1" vTcl:WidgetProc "Toplevel1" 1

    $top.scr50.01 configure -background white \
        -font font11 \
        -foreground black \
        -height 3 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    button $top.but51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command exit -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text Exit 
    vTcl:DefineAlias "$top.but51" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but44 \
        -background {#d9d9d9} -command help -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text ? 
    vTcl:DefineAlias "$top.but44" "Button4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -background {#d9d9d9} -font {-family {DejaVu Sans} -size 8} \
        -foreground {#000000} -text {Created by: Ivan & Kevin} 
    vTcl:DefineAlias "$top.lab46" "Label4" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but43 \
        -in $top -x 450 -y 190 -width 78 -relwidth 0 -height 41 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 210 -y 20 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 60 -y 100 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 130 -y 100 -anchor nw -bordermode ignore 
    place $top.ent52 \
        -in $top -x 100 -y 100 -width 26 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 170 -y 100 -width 26 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 270 -y 230 -width 166 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 270 -y 200 -width 166 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.ent57 \
        -in $top -x 270 -y 170 -width 166 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.ent59 \
        -in $top -x 360 -y 100 -width 166 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.tSe60 \
        -in $top -x 30 -y 60 -width 540 -anchor nw -bordermode inside 
    place $top.che64 \
        -in $top -x 210 -y 100 -anchor nw -bordermode ignore 
    place $top.che65 \
        -in $top -x 50 -y -80 -rely 0.366 -width 167 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.che67 \
        -in $top -x 47 -y 230 -width 147 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.che69 \
        -in $top -x 52 -y 200 -width 107 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 40 -y 300 -width 133 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSe44 \
        -in $top -x 60 -y 140 -width 470 -anchor nw -bordermode inside 
    place $top.tSe45 \
        -in $top -x 60 -y 280 -width 470 -anchor nw -bordermode inside 
    place $top.ent47 \
        -in $top -x 170 -y 300 -width 286 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 470 -y 300 -height 23 -relheight 0 -anchor nw \
        -bordermode ignore 
    place $top.tSe49 \
        -in $top -x 60 -y 350 -width 470 -anchor nw -bordermode inside 
    place $top.scr50 \
        -in $top -x 60 -y 370 -width 478 -relwidth 0 -height 257 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 260 -y 640 -anchor nw -bordermode ignore 
    place $top.but44 \
        -in $top -x 570 -y 10 -width 21 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 220 -y 676 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

