#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 14, 2019 04:56:37 PM CEST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import nmap_interface_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    nmap_interface_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    nmap_interface_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("962x624+489+200")
        top.title("Nmap Finder")
        top.configure(highlightcolor="black")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.395, rely=0.224, height=31, width=72)
        self.Button1.configure(activebackground="#f9f9f9")
        self.Button1.configure(command=nmap_interface_support.nmap)
        self.Button1.configure(text='''Search''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.208, rely=0.144,height=23, relwidth=0.266)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="-family {DejaVu Sans Mono} -size 10")
        self.Entry1.configure(selectbackground="#c4c4c4")

        self.Scrolledtext1 = ScrolledText(top)
        self.Scrolledtext1.place(relx=0.052, rely=0.337, relheight=0.572
                , relwidth=0.902)
        self.Scrolledtext1.configure(background="white")
        self.Scrolledtext1.configure(font="-family {DejaVu Sans} -size 10")
        self.Scrolledtext1.configure(insertborderwidth="3")
        self.Scrolledtext1.configure(selectbackground="#c4c4c4")
        self.Scrolledtext1.configure(width=10)
        self.Scrolledtext1.configure(wrap="none")

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.509, rely=0.08, relheight=0.208)
        self.TSeparator1.configure(orient="vertical")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.229, rely=0.032, height=21, width=117)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(text='''Basic Nmap Scan''')

        self.TSeparator2 = ttk.Separator(top)
        self.TSeparator2.place(relx=0.052, rely=0.08, relwidth=0.457)

        self.TSeparator3 = ttk.Separator(top)
        self.TSeparator3.place(relx=0.509, rely=0.08, relwidth=0.437)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.083, rely=0.144, height=21, width=98)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(text='''sudo nmap -A''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.665, rely=0.032, height=21, width=120)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(text='''Port Status Finder''')

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.541, rely=0.112, height=21, width=70)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(text='''Find port:''')

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.541, rely=0.16, height=21, width=128)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Find service name:''')

        self.Label6 = tk.Label(top)
        self.Label6.place(relx=0.541, rely=0.208, height=21, width=93)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(text='''Find Protocol:''')

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.707, rely=0.112,height=23, relwidth=0.131)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="-family {DejaVu Sans Mono} -size 10")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(state='disabled')

        self.Entry3 = tk.Entry(top)
        self.Entry3.place(relx=0.707, rely=0.16,height=23, relwidth=0.131)
        self.Entry3.configure(background="white")
        self.Entry3.configure(font="-family {DejaVu Sans Mono} -size 10")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(state='disabled')

        self.Entry4 = tk.Entry(top)
        self.Entry4.place(relx=0.707, rely=0.208,height=23, relwidth=0.131)
        self.Entry4.configure(background="white")
        self.Entry4.configure(font="-family {DejaVu Sans Mono} -size 10")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(state='disabled')

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.873, rely=0.112, height=25, width=46)
        self.Button2.configure(activebackground="#f9f9f9")
        self.Button2.configure(command=nmap_interface_support.port)
        self.Button2.configure(state='disabled')
        self.Button2.configure(text='''Go''')

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.873, rely=0.16, height=25, width=46)
        self.Button3.configure(activebackground="#f9f9f9")
        self.Button3.configure(command=nmap_interface_support.service)
        self.Button3.configure(state='disabled')
        self.Button3.configure(text='''Go''')

        self.Button4 = tk.Button(top)
        self.Button4.place(relx=0.873, rely=0.208, height=25, width=46)
        self.Button4.configure(activebackground="#f9f9f9")
        self.Button4.configure(command=nmap_interface_support.protocol)
        self.Button4.configure(state='disabled')
        self.Button4.configure(text='''Go''')

        self.Button5 = tk.Button(top)
        self.Button5.place(relx=0.956, rely=0.016, height=25, width=25)
        self.Button5.configure(activebackground="#f9f9f9")
        self.Button5.configure(command=nmap_interface_support.boton)
        self.Button5.configure(text='''?''')

        self.Button6 = tk.Button(top)
        self.Button6.place(relx=0.904, rely=0.929, height=31, width=53)
        self.Button6.configure(activebackground="#f9f9f9")
        self.Button6.configure(command=nmap_interface_support.exit)
        self.Button6.configure(text='''Exit''')

        self.Button7 = tk.Button(top)
        self.Button7.place(relx=0.052, rely=0.929, height=31, width=62)
        self.Button7.configure(activebackground="#f9f9f9")
        self.Button7.configure(command=nmap_interface_support.clear)
        self.Button7.configure(text='''Clear''')

        self.Button8 = tk.Button(top)
        self.Button8.place(relx=0.541, rely=0.272, height=31, width=79)
        self.Button8.configure(activebackground="#f9f9f9")
        self.Button8.configure(command=nmap_interface_support.attackMedusaSimple)
        self.Button8.configure(text='''Medusa''')

        self.Label7 = tk.Label(top)
        self.Label7.place(relx=0.416, rely=0.97, height=17, width=137)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(font="-family {DejaVu Sans} -size 8")
        self.Label7.configure(text='''Created by: Ivan & Kevin''')

        self.Button8_1 = tk.Button(top)
        self.Button8_1.place(relx=0.707, rely=0.272, height=31, width=207)
        self.Button8_1.configure(activebackground="#f9f9f9")
        self.Button8_1.configure(command=nmap_interface_support.attackMedusaCompo)
        self.Button8_1.configure(text='''Attack Range from Ports''')
        self.Button8_1.configure(width=207)

        self.Button9 = tk.Button(top)
        self.Button9.place(relx=0.052, rely=0.048, height=21, width=91)
        self.Button9.configure(command=nmap_interface_support.hardMode)
        self.Button9.configure(text='''Hard Mode''')
        self.Button9.configure(width=91)

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.post(event.x_root, event.y_root)

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, tk.Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()
